### PR TITLE
Heppy - fix typo/bug in random-cone variable in PhotonAnalyzer.py

### PR DESCRIPTION
**Pull request by mangano**

### CODE REVIEW

**Comment by pandolf** [comment]
@mangano you should do the same at line https://github.com/MT2Analysis/cmg-cmssw/blob/a21712701b9c3d9badb19e90866b7bad4e8c1116/PhysicsTools/Heppy/python/analyzers/objects/PhotonAnalyzer.py#L233

**Comment by mangano** [comment]
But then also the previous lines should be adapted? 

```
      if gamma.chHadIsoRC>=0. : continue #good to go

      if gamma.chHadIsoRC04>=0. : continue #good to go
```

Otherwise it crashes. 

Is the change correct? or in the if I should use RC03  in the if statement??

**Comment by pandolf** [comment]
ah you're right!

you should modify the code to look like this:

```
gamma.chHadIsoRC03 = self.computeRandomCone( event, etaPhot, phiRC, 0.3, charged, jets20, photons10 )
gamma.chHadIsoRC04 = self.computeRandomCone( event, etaPhot, phiRC, 0.4, charged, jets20, photons10 )


#try other side
phiRC = phiPhot - 0.5*pi
while phiRC<-pi:
  phiRC += 2.*pi

if gamma.chHadIsoRC03<0. : gamma.chHadIsoRC03 = self.computeRandomCone( event, etaPhot, phiRC, 0.3, charged, jets20, photons10 )
if gamma.chHadIsoRC04<0. : gamma.chHadIsoRC04 = self.computeRandomCone( event, etaPhot, phiRC, 0.4, charged, jets20, photons10 )
```

**Comment by mangano** [comment]
The jobs that are currently running have what is below. Should I kill them? 

 for gamma in event.allphotons:

```
      etaPhot = gamma.eta()
      phiPhot = gamma.eta()
      pi = 3.14159
      phiRC = phiPhot + 0.5*pi
      while phiRC>pi:
        phiRC -= 2.*pi

      gamma.chHadIsoRC03 = self.computeRandomCone( event, etaPhot, phiRC, 0.3, charged, jets20, photons10 )
      gamma.chHadIsoRC04 = self.computeRandomCone( event, etaPhot, phiRC, 0.4, charged, jets20, photons10 )

      if gamma.chHadIsoRC04>=0. : continue #good to go

      #if not, try other side:
      phiRC = phiPhot - 0.5*pi
      while phiRC<-pi:
        phiRC += 2.*pi

      gamma.chHadIsoRC03 = self.computeRandomCone( event, etaPhot, phiRC, 0.3, charged, jets20, photons10 )
      gamma.chHadIsoRC04 = self.computeRandomCone( event, etaPhot, phiRC, 0.4, charged, jets20, photons10 )
```

**Pull request merged**
